### ISSUE TITLE
What are the drawbacks of using this library over single case discriminated unions?

### ISSUE THREAD

**Issue by nkosi23** [fsprojects/FSharp.UMX#32]
Hello,

This library looks neat and I am very tempted to replace our use of single-case discriminated unions with unit of measures since we mostly use them to strongly type id types.

however I wonder if there are drawbacks i should be aware of before making such a move (such as for example, build time increase or things like that)

**Comment by bartelink** [comment]
Read the 4 part series in https://paul.blasuc.ci/posts/really-scu.html
possibly send a PR adding links to it here

No, there's no significant compile time tax, as there is for some esoteric constructs like some serialization extensions and/or some common generic libraties
