### ISSUE TITLE
Move to fsprojects?

### ISSUE THREAD

**Issue by eiriktsarpalis** [fsprojects/FSharp.UMX#7]
Perhaps we could move the repo to github.com/fsprojects for bigger visibility

**Comment by alfonsogarciacaro** [comment]
That makes a lot of sense! What was the process for that? Should I give @sergey-tihon admin rights so he can move the repo?

**Comment by sergey-tihon** [comment]
@alfonsogarciacaro this may work
but the formal process is here - https://github.com/fsprojects/FsProjectsAdmin

**Comment by bartelink** [comment]
While we're talking - `.Extra` (or `x` appendages etc) stuff in general I don't find useful in names.

Maybe something like `UnitOfType` ( `FSharp.UnitOfType` if it has to be given it actually is a pretty lang specific concept). `UomTag`, `TypeTags`)

**Comment by alfonsogarciacaro** [comment]
@sergey-tihon Ok, I sent you an invite link :)

@bartelink Yes, I agree `Extra` is not very good but I did wanted to convey the meaning the lib provides some extra units of measure beyond the standard (numeric) ones. I'd prefer to avoid the `FSharp.` prefix (as this is not a Microsoft package) and abbreviations in the namespace, but I'm open to any other name :)

**Comment by bartelink** [comment]
Good point re the `FSharp`. I guess my reason for not wanting `UnitOfMeasure` in full directly in the name and/or putting `.Extra` is that, while it's using UOM to achieve it's ends, it's really achieving a result on a pretty different axis. My other concern is that it's a pretty singular thing, and naming it that way versus suggesting it's from a big family of things you might need to consider. More names I'm not entirely happy with: `UnitOfKind`, `UnitOfTag` ?

**Comment by sergey-tihon** [comment]
@alfonsogarciacaro owner access does not let me  transfer it =( I've send you invitation to `fsprojects-transfer` org owner, please transfer project there and then I'll move to `fsprojects`

**Comment by alfonsogarciacaro** [comment]
@sergey-tihon Done, thank you! :+1:

**Comment by sergey-tihon** [comment]
@alfonsogarciacaro done!

**Comment by bartelink** [comment]
Nice - now, about that name ;P My weightings for name segments, in an attempt to spark a debate:

-   -1 `Extra`
- +0.2 `FSharp.`
- +0.4 `UnitOf`
- -.5 `Measure` (we are not measuring anything)
- +.2 `Id`
- +.5 `Type`

**Comment by eiriktsarpalis** [comment]
`FSharp.UMX` "unit of measure extensions"
